[package]
name = "demo"
version = "0.1.0"
authors = ["Luis Vega <vegaluisjose@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
